# coding: utf-8

"""
    IDaaS API

    Identity as a Service API for member authentication, identifiers, and account management.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_idaas_sdk.models.ftc_identify_url_response import FtcIdentifyUrlResponse

class TestFtcIdentifyUrlResponse(unittest.TestCase):
    """FtcIdentifyUrlResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FtcIdentifyUrlResponse:
        """Test FtcIdentifyUrlResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FtcIdentifyUrlResponse`
        """
        model = FtcIdentifyUrlResponse()
        if include_optional:
            return FtcIdentifyUrlResponse(
                url = 'https://laca.example.com/ftc/begin/123/abc123xyz/1',
                qr = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...'
            )
        else:
            return FtcIdentifyUrlResponse(
        )
        """

    def testFtcIdentifyUrlResponse(self):
        """Test FtcIdentifyUrlResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
