# coding: utf-8

"""
    IDaaS API

    Identity as a Service API for member authentication, identifiers, and account management.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_idaas_sdk.models.auth_error_response import AuthErrorResponse

class TestAuthErrorResponse(unittest.TestCase):
    """AuthErrorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthErrorResponse:
        """Test AuthErrorResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthErrorResponse`
        """
        model = AuthErrorResponse()
        if include_optional:
            return AuthErrorResponse(
                error = api_idaas_sdk.models.auth_error_response_error.AuthErrorResponse_error(
                    message = 'Access denied', 
                    reason = 'The token is invalid or expired', )
            )
        else:
            return AuthErrorResponse(
        )
        """

    def testAuthErrorResponse(self):
        """Test AuthErrorResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
