# coding: utf-8

"""
    IDaaS API

    Identity as a Service API for member authentication, identifiers, and account management.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_idaas_sdk.models.identify_request_body import IdentifyRequestBody

class TestIdentifyRequestBody(unittest.TestCase):
    """IdentifyRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IdentifyRequestBody:
        """Test IdentifyRequestBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IdentifyRequestBody`
        """
        model = IdentifyRequestBody()
        if include_optional:
            return IdentifyRequestBody(
                connection_nid = '123',
                connection_token_hash = 'abc123hashed',
                return_to = 'https://example.com/callback',
                linking_token = 'unique_linking_token'
            )
        else:
            return IdentifyRequestBody(
                connection_nid = '123',
                connection_token_hash = 'abc123hashed',
                return_to = 'https://example.com/callback',
        )
        """

    def testIdentifyRequestBody(self):
        """Test IdentifyRequestBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
