# coding: utf-8

"""
    IDaaS API

    Identity as a Service API for member authentication, identifiers, and account management.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_idaas_sdk.models.update_notification_status_request_body import UpdateNotificationStatusRequestBody

class TestUpdateNotificationStatusRequestBody(unittest.TestCase):
    """UpdateNotificationStatusRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateNotificationStatusRequestBody:
        """Test UpdateNotificationStatusRequestBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateNotificationStatusRequestBody`
        """
        model = UpdateNotificationStatusRequestBody()
        if include_optional:
            return UpdateNotificationStatusRequestBody(
                identifier = '550e8400-e29b-41d4-a716-446655440000'
            )
        else:
            return UpdateNotificationStatusRequestBody(
                identifier = '550e8400-e29b-41d4-a716-446655440000',
        )
        """

    def testUpdateNotificationStatusRequestBody(self):
        """Test UpdateNotificationStatusRequestBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
