# coding: utf-8

"""
    IDaaS API

    Identity as a Service API for member authentication, identifiers, and account management.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_idaas_sdk.models.get_invite_response import GetInviteResponse

class TestGetInviteResponse(unittest.TestCase):
    """GetInviteResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetInviteResponse:
        """Test GetInviteResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetInviteResponse`
        """
        model = GetInviteResponse()
        if include_optional:
            return GetInviteResponse(
                success = 1,
                invite_url_code = 'a1b2c3d4e5f6',
                parent_uuid = '550e8400-e29b-41d4-a716-446655440000',
                app_url = 'https://example.com',
                client_id = 'client123',
                con_nid = '456',
                org_id = 'org789',
                project_id = 'proj123',
                item_id = 'item456',
                type = 'identifier'
            )
        else:
            return GetInviteResponse(
        )
        """

    def testGetInviteResponse(self):
        """Test GetInviteResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
