# coding: utf-8

"""
    IDaaS API

    Identity as a Service API for member authentication, identifiers, and account management.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_idaas_sdk.models.ftc_setup_request_body import FtcSetupRequestBody

class TestFtcSetupRequestBody(unittest.TestCase):
    """FtcSetupRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FtcSetupRequestBody:
        """Test FtcSetupRequestBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FtcSetupRequestBody`
        """
        model = FtcSetupRequestBody()
        if include_optional:
            return FtcSetupRequestBody(
                connection_nid = '123',
                connection_token_hash = 'abc123hashed',
                return_to = 'https://example.com/callback',
                mydexid = 'mydex123',
                version = 1,
                linking_token = 'unique_linking_token'
            )
        else:
            return FtcSetupRequestBody(
                connection_nid = '123',
                connection_token_hash = 'abc123hashed',
                return_to = 'https://example.com/callback',
        )
        """

    def testFtcSetupRequestBody(self):
        """Test FtcSetupRequestBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
