# coding: utf-8

"""
    IDaaS API

    Identity as a Service API for member authentication, identifiers, and account management.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_idaas_sdk.api.connections_api import ConnectionsApi


class TestConnectionsApi(unittest.TestCase):
    """ConnectionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConnectionsApi()

    def tearDown(self) -> None:
        pass

    def test_post_ftc_setup(self) -> None:
        """Test case for post_ftc_setup

        Set up a First Time Connection URL.
        """
        pass

    def test_post_identify(self) -> None:
        """Test case for post_identify

        Set up an identification URL.
        """
        pass


if __name__ == '__main__':
    unittest.main()
