# coding: utf-8

"""
    IDaaS API

    Identity as a Service API for member authentication, identifiers, and account management.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_idaas_sdk.api.identifiers_api import IdentifiersApi


class TestIdentifiersApi(unittest.TestCase):
    """IdentifiersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IdentifiersApi()

    def tearDown(self) -> None:
        pass

    def test_get_identifier_invite(self) -> None:
        """Test case for get_identifier_invite

        Fetch an invitation code and identifier auth data.
        """
        pass

    def test_patch_notify_status(self) -> None:
        """Test case for patch_notify_status

        Update the status of a notification.
        """
        pass

    def test_post_invite_status(self) -> None:
        """Test case for post_invite_status

        Check the status of an invite.
        """
        pass

    def test_post_notify_member_via_identifier(self) -> None:
        """Test case for post_notify_member_via_identifier

        Send a notification to a member via its identifier.
        """
        pass

    def test_post_store_and_send_identifier_invite(self) -> None:
        """Test case for post_store_and_send_identifier_invite

        Store an invitation code and send notification.
        """
        pass


if __name__ == '__main__':
    unittest.main()
