# coding: utf-8

"""
    IDaaS API

    Identity as a Service API for member authentication, identifiers, and account management.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_idaas_sdk.models.invite_request_body import InviteRequestBody

class TestInviteRequestBody(unittest.TestCase):
    """InviteRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InviteRequestBody:
        """Test InviteRequestBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InviteRequestBody`
        """
        model = InviteRequestBody()
        if include_optional:
            return InviteRequestBody(
                identifier = '550e8400-e29b-41d4-a716-446655440000',
                app_url = 'https://example.com',
                client_id = 'client123',
                con_nid = '456',
                org_id = 'org789',
                project_id = 'proj123',
                item_id = 'item456',
                type = 'identifier',
                message_email = 'Please complete your registration',
                message_sms = 'Please complete your registration'
            )
        else:
            return InviteRequestBody(
                identifier = '550e8400-e29b-41d4-a716-446655440000',
                app_url = 'https://example.com',
                client_id = 'client123',
                con_nid = '456',
                org_id = 'org789',
                project_id = 'proj123',
                item_id = 'item456',
                type = 'identifier',
                message_email = 'Please complete your registration',
        )
        """

    def testInviteRequestBody(self):
        """Test InviteRequestBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
