# coding: utf-8

"""
    IDaaS API

    Identity as a Service API for member authentication, identifiers, and account management.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_idaas_sdk.models.identifier_object import IdentifierObject

class TestIdentifierObject(unittest.TestCase):
    """IdentifierObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IdentifierObject:
        """Test IdentifierObject
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IdentifierObject`
        """
        model = IdentifierObject()
        if include_optional:
            return IdentifierObject(
                id = '123',
                identifier = '550e8400-e29b-41d4-a716-446655440000',
                parent_uuid = '660e8400-e29b-41d4-a716-446655440000',
                type = 'identifier',
                created = '2024-01-15 10:30:00'
            )
        else:
            return IdentifierObject(
        )
        """

    def testIdentifierObject(self):
        """Test IdentifierObject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
