# coding: utf-8

"""
    IDaaS API

    Identity as a Service API for member authentication, identifiers, and account management.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_idaas_sdk.api.my_account_api import MyAccountApi


class TestMyAccountApi(unittest.TestCase):
    """MyAccountApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MyAccountApi()

    def tearDown(self) -> None:
        pass

    def test_get_mydex_id_from_my_account_svt(self) -> None:
        """Test case for get_mydex_id_from_my_account_svt

        Check if a MyAccount SVT has an associated MydexID.
        """
        pass


if __name__ == '__main__':
    unittest.main()
