# coding: utf-8

"""
    IDaaS API

    Identity as a Service API for member authentication, identifiers, and account management.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_idaas_sdk.models.auth_error_response_error import AuthErrorResponseError

class TestAuthErrorResponseError(unittest.TestCase):
    """AuthErrorResponseError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthErrorResponseError:
        """Test AuthErrorResponseError
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthErrorResponseError`
        """
        model = AuthErrorResponseError()
        if include_optional:
            return AuthErrorResponseError(
                message = 'Access denied',
                reason = 'The token is invalid or expired'
            )
        else:
            return AuthErrorResponseError(
        )
        """

    def testAuthErrorResponseError(self):
        """Test AuthErrorResponseError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
