# coding: utf-8

"""
    IDaaS API

    Identity as a Service API for member authentication, identifiers, and account management.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_idaas_sdk.models.identify_url_response import IdentifyUrlResponse

class TestIdentifyUrlResponse(unittest.TestCase):
    """IdentifyUrlResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IdentifyUrlResponse:
        """Test IdentifyUrlResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IdentifyUrlResponse`
        """
        model = IdentifyUrlResponse()
        if include_optional:
            return IdentifyUrlResponse(
                url = 'https://login.mydex.org/identify/123/abc123xyz',
                qr = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...'
            )
        else:
            return IdentifyUrlResponse(
        )
        """

    def testIdentifyUrlResponse(self):
        """Test IdentifyUrlResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
