# coding: utf-8

"""
    IDaaS API

    Identity as a Service API for member authentication, identifiers, and account management.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from api_idaas_sdk.api.scot_account_api import ScotAccountApi


class TestScotAccountApi(unittest.TestCase):
    """ScotAccountApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ScotAccountApi()

    def tearDown(self) -> None:
        pass

    def test_get_mydex_id_from_scot_account_sub(self) -> None:
        """Test case for get_mydex_id_from_scot_account_sub

        Check if a ScotAccount sub GUID has an associated MydexID.
        """
        pass


if __name__ == '__main__':
    unittest.main()
