# coding: utf-8

# flake8: noqa

"""
    IDaaS API

    Identity as a Service API for member authentication, identifiers, and account management.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "ConnectionsApi",
    "IdentifiersApi",
    "MyAccountApi",
    "ScotAccountApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AuthErrorResponse",
    "AuthErrorResponseError",
    "CreateIdentifierResponse",
    "ErrorResponse",
    "FtcIdentifyUrlResponse",
    "FtcSetupRequestBody",
    "FtcUrlResponse",
    "GetIdentifiersResponse",
    "GetInviteResponse",
    "IdentifierAuthObject",
    "IdentifierObject",
    "IdentifyRequestBody",
    "IdentifyUrlResponse",
    "InviteRequestBody",
    "InviteStatusRequestBody",
    "InviteStatusResponse",
    "NotifyMemberRequestBody",
    "UpdateNotificationStatusRequestBody",
]

# import apis into sdk package
from api_idaas_sdk.api.connections_api import ConnectionsApi as ConnectionsApi
from api_idaas_sdk.api.identifiers_api import IdentifiersApi as IdentifiersApi
from api_idaas_sdk.api.my_account_api import MyAccountApi as MyAccountApi
from api_idaas_sdk.api.scot_account_api import ScotAccountApi as ScotAccountApi

# import ApiClient
from api_idaas_sdk.api_response import ApiResponse as ApiResponse
from api_idaas_sdk.api_client import ApiClient as ApiClient
from api_idaas_sdk.configuration import Configuration as Configuration
from api_idaas_sdk.exceptions import OpenApiException as OpenApiException
from api_idaas_sdk.exceptions import ApiTypeError as ApiTypeError
from api_idaas_sdk.exceptions import ApiValueError as ApiValueError
from api_idaas_sdk.exceptions import ApiKeyError as ApiKeyError
from api_idaas_sdk.exceptions import ApiAttributeError as ApiAttributeError
from api_idaas_sdk.exceptions import ApiException as ApiException

# import models into sdk package
from api_idaas_sdk.models.auth_error_response import AuthErrorResponse as AuthErrorResponse
from api_idaas_sdk.models.auth_error_response_error import AuthErrorResponseError as AuthErrorResponseError
from api_idaas_sdk.models.create_identifier_response import CreateIdentifierResponse as CreateIdentifierResponse
from api_idaas_sdk.models.error_response import ErrorResponse as ErrorResponse
from api_idaas_sdk.models.ftc_identify_url_response import FtcIdentifyUrlResponse as FtcIdentifyUrlResponse
from api_idaas_sdk.models.ftc_setup_request_body import FtcSetupRequestBody as FtcSetupRequestBody
from api_idaas_sdk.models.ftc_url_response import FtcUrlResponse as FtcUrlResponse
from api_idaas_sdk.models.get_identifiers_response import GetIdentifiersResponse as GetIdentifiersResponse
from api_idaas_sdk.models.get_invite_response import GetInviteResponse as GetInviteResponse
from api_idaas_sdk.models.identifier_auth_object import IdentifierAuthObject as IdentifierAuthObject
from api_idaas_sdk.models.identifier_object import IdentifierObject as IdentifierObject
from api_idaas_sdk.models.identify_request_body import IdentifyRequestBody as IdentifyRequestBody
from api_idaas_sdk.models.identify_url_response import IdentifyUrlResponse as IdentifyUrlResponse
from api_idaas_sdk.models.invite_request_body import InviteRequestBody as InviteRequestBody
from api_idaas_sdk.models.invite_status_request_body import InviteStatusRequestBody as InviteStatusRequestBody
from api_idaas_sdk.models.invite_status_response import InviteStatusResponse as InviteStatusResponse
from api_idaas_sdk.models.notify_member_request_body import NotifyMemberRequestBody as NotifyMemberRequestBody
from api_idaas_sdk.models.update_notification_status_request_body import UpdateNotificationStatusRequestBody as UpdateNotificationStatusRequestBody

