# coding: utf-8

"""
    IDaaS API

    Identity as a Service API for member authentication, identifiers, and account management.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GetInviteResponse(BaseModel):
    """
    Response when getting an invitation
    """ # noqa: E501
    success: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [1]})
    invite_url_code: Optional[StrictStr] = Field(default=None, description="The invitation URL code", json_schema_extra={"examples": ["a1b2c3d4e5f6"]})
    parent_uuid: Optional[UUID] = Field(default=None, description="The parent identifier UUID", json_schema_extra={"examples": ["550e8400-e29b-41d4-a716-446655440000"]})
    app_url: Optional[StrictStr] = Field(default=None, description="The application URL", json_schema_extra={"examples": ["https://example.com"]})
    client_id: Optional[StrictStr] = Field(default=None, description="The OAuth2 client ID", json_schema_extra={"examples": ["client123"]})
    con_nid: Optional[StrictStr] = Field(default=None, description="The connection NID", json_schema_extra={"examples": ["456"]})
    org_id: Optional[StrictStr] = Field(default=None, description="The organization ID", json_schema_extra={"examples": ["org789"]})
    project_id: Optional[StrictStr] = Field(default=None, description="The project ID", json_schema_extra={"examples": ["proj123"]})
    item_id: Optional[StrictStr] = Field(default=None, description="The item ID", json_schema_extra={"examples": ["item456"]})
    type: Optional[StrictStr] = Field(default=None, description="The type of invitation", json_schema_extra={"examples": ["identifier"]})
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["success", "invite_url_code", "parent_uuid", "app_url", "client_id", "con_nid", "org_id", "project_id", "item_id", "type"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetInviteResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if org_id (nullable) is None
        # and model_fields_set contains the field
        if self.org_id is None and "org_id" in self.model_fields_set:
            _dict['org_id'] = None

        # set to None if project_id (nullable) is None
        # and model_fields_set contains the field
        if self.project_id is None and "project_id" in self.model_fields_set:
            _dict['project_id'] = None

        # set to None if item_id (nullable) is None
        # and model_fields_set contains the field
        if self.item_id is None and "item_id" in self.model_fields_set:
            _dict['item_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetInviteResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "success": obj.get("success"),
            "invite_url_code": obj.get("invite_url_code"),
            "parent_uuid": obj.get("parent_uuid"),
            "app_url": obj.get("app_url"),
            "client_id": obj.get("client_id"),
            "con_nid": obj.get("con_nid"),
            "org_id": obj.get("org_id"),
            "project_id": obj.get("project_id"),
            "item_id": obj.get("item_id"),
            "type": obj.get("type")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


