# coding: utf-8

"""
    IDaaS API

    Identity as a Service API for member authentication, identifiers, and account management.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class IdentifierObject(BaseModel):
    """
    An identifier record
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Database ID of the identifier", json_schema_extra={"examples": ["123"]})
    identifier: Optional[UUID] = Field(default=None, description="The UUID identifier", json_schema_extra={"examples": ["550e8400-e29b-41d4-a716-446655440000"]})
    parent_uuid: Optional[UUID] = Field(default=None, description="The parent identifier UUID if this is a child", json_schema_extra={"examples": ["660e8400-e29b-41d4-a716-446655440000"]})
    type: Optional[StrictStr] = Field(default=None, description="The type of identifier", json_schema_extra={"examples": ["identifier"]})
    created: Optional[StrictStr] = Field(default=None, description="Creation timestamp", json_schema_extra={"examples": ["2024-01-15 10:30:00"]})
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "identifier", "parent_uuid", "type", "created"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IdentifierObject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if parent_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.parent_uuid is None and "parent_uuid" in self.model_fields_set:
            _dict['parent_uuid'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IdentifierObject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "identifier": obj.get("identifier"),
            "parent_uuid": obj.get("parent_uuid"),
            "type": obj.get("type"),
            "created": obj.get("created")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


