# coding: utf-8

"""
    IDaaS API

    Identity as a Service API for member authentication, identifiers, and account management.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class IdentifyRequestBody(BaseModel):
    """
    Request body for identification URL setup
    """ # noqa: E501
    connection_nid: StrictStr = Field(description="The connection NID", json_schema_extra={"examples": ["123"]})
    connection_token_hash: StrictStr = Field(description="The hashed connection token", json_schema_extra={"examples": ["abc123hashed"]})
    return_to: StrictStr = Field(description="The URL to return to after identification", json_schema_extra={"examples": ["https://example.com/callback"]})
    linking_token: Optional[StrictStr] = Field(default=None, description="A unique ID representing the member in the subscriber's backend", json_schema_extra={"examples": ["unique_linking_token"]})
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["connection_nid", "connection_token_hash", "return_to", "linking_token"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IdentifyRequestBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if linking_token (nullable) is None
        # and model_fields_set contains the field
        if self.linking_token is None and "linking_token" in self.model_fields_set:
            _dict['linking_token'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IdentifyRequestBody from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "connection_nid": obj.get("connection_nid"),
            "connection_token_hash": obj.get("connection_token_hash"),
            "return_to": obj.get("return_to"),
            "linking_token": obj.get("linking_token")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


