# coding: utf-8

"""
    IDaaS API

    Identity as a Service API for member authentication, identifiers, and account management.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from api_idaas_sdk.models.identifier_auth_object import IdentifierAuthObject
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class NotifyMemberRequestBody(BaseModel):
    """
    Request body for sending a notification to a member
    """ # noqa: E501
    identifier_auth: IdentifierAuthObject
    message_email: StrictStr = Field(description="Email message content", json_schema_extra={"examples": ["Please verify your identity"]})
    message_sms: Optional[StrictStr] = Field(default=None, description="SMS message content", json_schema_extra={"examples": ["Please verify your identity"]})
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["identifier_auth", "message_email", "message_sms"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NotifyMemberRequestBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of identifier_auth
        if self.identifier_auth:
            _dict['identifier_auth'] = self.identifier_auth.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if message_sms (nullable) is None
        # and model_fields_set contains the field
        if self.message_sms is None and "message_sms" in self.model_fields_set:
            _dict['message_sms'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NotifyMemberRequestBody from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "identifier_auth": IdentifierAuthObject.from_dict(obj["identifier_auth"]) if obj.get("identifier_auth") is not None else None,
            "message_email": obj.get("message_email"),
            "message_sms": obj.get("message_sms")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


